{
  "formatVersion": "1.1",
  "component": {
    "group": "com.honor.iap-core",
    "module": "iap-sdk-comm",
    "version": "0.2.3.18",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId": "kjiti4b4snhwpkrqfsxmuqfafm"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "iap-sdk-comm-0.2.3.18.aar",
          "url": "iap-sdk-comm-0.2.3.18.aar",
          "size": 41327,
          "sha512": "2f86ef56bb875dad49e82ecebac7840cc599312b3fe58867cf27515cf4980c52e0858935b77baea655d9041f93cc69ccc50da065280fb28114a13addc51ee3b4",
          "sha256": "ecb643328711179703cba7bec84de65a6252bca6b7f5c0a43edad6ce218b3437",
          "sha1": "5966dcf79531f8df54b3a4e52207b4ad337e5998",
          "md5": "0776aab26e5d78242d66efc4912e97ed"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "iap-sdk-comm-0.2.3.18.aar",
          "url": "iap-sdk-comm-0.2.3.18.aar",
          "size": 41327,
          "sha512": "2f86ef56bb875dad49e82ecebac7840cc599312b3fe58867cf27515cf4980c52e0858935b77baea655d9041f93cc69ccc50da065280fb28114a13addc51ee3b4",
          "sha256": "ecb643328711179703cba7bec84de65a6252bca6b7f5c0a43edad6ce218b3437",
          "sha1": "5966dcf79531f8df54b3a4e52207b4ad337e5998",
          "md5": "0776aab26e5d78242d66efc4912e97ed"
        }
      ]
    }
  ]
}
